### PR TITLE
Added new method to join array using comma as separator.

### PR DESCRIPTION
**Pull request by jesuslg123**
As starting to look into the project I just started with an small improvement on how to create the parameters strings comma separated from the array.

I hope have time to be helping you on it, is quite nice app :)

### CODE REVIEW

**Comment by jesuslg123** [comment]
I just saw a mac os demo app on xiaomi site, could be used as reference as well. 
https://www.yeelight.com/en_US/developer
https://www.yeelight.com/download/developer/yeelight_local_mac_demo.zip

**Comment by alessandro308** [comment]
The demo app is quite intricated. Some parts are written in Chinese and no so interesting features are available. I prefer to refer to Developer Protocol Specification.

I need to build a new UI for the Yeelight class. If you would like, this is the new step =)

**Comment by jesuslg123** [comment]
Any design suggestion? :)

This is the plan??
https://camo.githubusercontent.com/4197cb4089e7ec9692320a4715b08215a49d4f43/68747470733a2f2f696d6167652e6962622e636f2f6861573177772f707265766965772e706e67

**Comment by alessandro308** [comment]
Any design you want. In any case, there is a previous version design in the main README file

**Pull request merged**
